### PR TITLE
[CogSvcs] Updated Translate.py Sample

### PR DESCRIPTION
**Pull request by erhopf**
I've updated the sample to run on Python 2.7.x and 3.x. Also, I've opted to use the requests library and provide instructions to read the subscription key from an env variable. I've reviewed the changes with @Jann-Skotdal  and have updates ready to deploy to docs.microsoft.com as soon as the sample is updated. 

Thx!

### CODE REVIEW

**Comment by Jann-Skotdal** [comment]
#sign-off

**Comment by Jann-Skotdal** [comment]
@kellyaltom Can you review this code sample update from Erik?

**Comment by kellyaltom** [comment]
It looks fine to me. Should not be any issues since there is only one person working on this sample


________________________________

**Comment by erhopf** [comment]
@Jann-Skotdal - License has been added. It's ready to merge whenever you're ready ;)

**Pull request merged**
